Repository dynawo/dynawo-algorithms, pull requests merged in 2021-12, with the labels that each got.

#128 #127 Fix timeline entry set
  sources/Launcher/DYNMarginCalculationLauncher.cpp
  sources/Launcher/DYNSystematicAnalysisLauncher.cpp
Labels: bug, MC, SA

#124 #81 Use generic cmake generators
  util/envDynawoAlgorithms.sh
Labels: enhancement

#135 #134 Launcher depends on revision tag
  sources/Launcher/CMakeLists.txt
Labels: bug, DevOps
