Repository dynawo/dynawo-algorithms, pull requests merged in 2021-11, with the labels that each got.

#108 #98 fix stringstream copy
  sources/Common/DYNSimulationResult.cpp
Labels: bug

#113 #112 Remove timeline print in double. Remove timeline print in files …
  sources/Launcher/DYNMarginCalculationLauncher.cpp
Labels: MC

#119 #118 Improve readme
  README.md
Labels: documentation

#120 #117 Adapt start and stop time
  nrt/data/IEEE14/MC/reference/aggregatedResults.xml
  nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml
  nrt/data/IEEE14/MC_file/reference/aggregatedResults.xml
  nrt/data/IEEE14/MC_file_local/reference/aggregatedResults.xml
  sources/Launcher/DYNMarginCalculationLauncher.cpp
  sources/Launcher/DYNMarginCalculationLauncher.h
  sources/Launcher/DYNMultiVariantInputs.h
  sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
  sources/Launcher/DYNRobustnessAnalysisLauncher.h
Labels: enhancement

#86 #82 Add directory in deploy to comply with dynawo
  util/envDynawoAlgorithms.sh
Labels: enhancement

#121 #93 Fix local margin computation.
  sources/Launcher/DYNMarginCalculationLauncher.cpp
Labels: bug, MC
