Repository dynawo/dynawo-algorithms, pull requests merged in 2022-01, with the labels that each got.

#139 #138 remove quoting for CMAKE_OPTIONAL
  util/envDynawoAlgorithms.sh
Labels: bug, DevOps

#166 #148 Fix name of dynawo release used in release workflow.
  .github/workflows/release.yml
Labels: DevOps

#145 #117 Fix adapt start and stop time, event was added two times.
  sources/Launcher/DYNMarginCalculationLauncher.cpp
Labels: bug, MC, On-Hold

#175 #174 Fix load increase fails at zero
  sources/Launcher/DYNMarginCalculationLauncher.cpp
Labels: bug, MC
